[package]
name = "multisigverifier-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.multisigverifier]
path = ".."

[dependencies.dharitri-sc-meta]
version = "0.13.6"
default-features = false
