[package]
name = "chain-config-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.chain-config]
path = ".."

[dependencies.dharitri-sc-meta]
version = "=0.13.6"
