[package]
name = "bls-signature"
version = "0.0.0"
authors = ["dorin-iancu <dorin.iancu@dharitri.com>"]
edition = "2018"

[dependencies.dharitri-sc]
version = "=0.13.6"

[dev-dependencies.dharitri-sc-scenario]
version = "=0.13.6"

[dependencies.transaction]
path = "../transaction"
